' ******************************************************************************
' swxJRNL.swj - journal recorded on 12/26/25 by takaki
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "swerve.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Arm_2_ver2-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Vacume end effector-1@swerve", "COMPONENT", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arm_4-1@swerve", "COMPONENT", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arm_3-1@swerve", "COMPONENT", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Arm_1_ver2-1@swerve", "COMPONENT", 0, 0, 0, True, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("ｽｹｯﾁ7", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("ｽｹｯﾁ8", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("ｽｹｯﾁ9", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("ｽｹｯﾁ10", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ1", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_steer1_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ2", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_drive1_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ3", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_steer2_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ4", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_drive2_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ5", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_steer3_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ6", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_drive3_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ7", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_steer4_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ8", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_drive4_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ9", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ10", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ11", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ12", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ13", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_yaw_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ14", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ15", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ16", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ17", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ10", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ11", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ12", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ13", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_yaw_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ14", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ15", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ16", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ17", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ9", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ10", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ11", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ12", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ13", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_yaw_joint", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ14", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link1_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ15", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link2_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ16", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_link3_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("3Dｽｹｯﾁ17", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Axis_wrist_joint2", "AXIS", 0, 0, 0, True, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("base_yaw", "COORDSYS", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("ｽｹｯﾁ6", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("base_yaw", "COORDSYS", 0, 0, 0, True, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06528622233241303252, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05841398840268535037, -0.02915953402226997143
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05497787143782150582, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.05154175447295766127, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("UST-30LX - コピー-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("UST-30LX - コピー-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("UST-30LX - コピー-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Dim swcomp As Object
Set swcomp = Part.SelectionManager.GetSelectedObject6(1, -1)
boolstatus = swcomp.MakeVirtual2(True)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Copy of UST-30LX - コピー^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Base^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Copy of UST-30LX - コピー^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Copy of UST-30LX - コピー^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Copy of UST-30LX - コピー^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)

' Rename Virtual Component
Dim swSelMgr As SelectionMgr
Set swSelMgr = Part.SelectionManager
Dim swComp As Component2
Set swComp = swSelMgr.GetSelectedObject6(1, -1)
swComp.Name2 = "UST-30LX"
boolstatus = Part.Extension.SelectByID2("UST-30LX^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.05102918453897244827, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, 0.01457976701113498572, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01457976701113498572, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01457976701113498572, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01457976701113498572, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007289883505567492858, 0.2022889354079211444, -0.01433948914689153753, 0.04101408473496803708

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("UST-30LX^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("UST-30LX^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
' MSGBOX
' UST-30LX 同じ名前を持ったｷｭﾒﾝﾄが既に開いています。仮想の構成部品をこの名前に変えられることはできません。


' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
boolstatus = Part.Extension.SelectByID2("UST-30LX^swerve-1@swerve", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
' MSGBOX
' UST-30LX 同じ名前を持ったｷｭﾒﾝﾄが既に開いています。仮想の構成部品をこの名前に変えられることはできません。

Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.06560895155010743052
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.05102918453897244827
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.03644941752783745909
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.04373930103340495368
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04466952054322997218, -0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007289883505567492858
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02915953402226997143
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02915953402226997143
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02186965051670247684
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01457976701113498572
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007289883505567492858

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Save
boolstatus = Part.Save3(1, swErrors, swWarnings)

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "swerve.SLDASM"
